apiVersion: v1
kind: ConfigMap
metadata:
  name: fffffff-config
  namespace: namespace-workflow-1744674179810
  labels:
    app.kubernetes.io/name: fffffff
    kubernetes.azure.com/generator: devhub
data: