apiVersion: apps/v1
kind: Deployment
metadata:
  name: davidgamero-test2
  labels:
    app: davidgamero-test2
  namespace: namespace-workflow-1695051455078
spec:
  replicas: 1
  selector:
    matchLabels:
      app: davidgamero-test2
  template:
    metadata:
      labels:
        app: davidgamero-test2
    spec:
      containers:
        - name: davidgamero-test2
          image: acrworkflow1695051455078.azurecr.io/image-workflow-1695051455078:latest
          ports:
            - containerPort: 1323