apiVersion: apps/v1
kind: Deployment
metadata:
  name: davidgamero-test3
  labels:
    app: davidgamero-test3
  namespace: namespace-workflow-1688155414377
spec:
  replicas: 1
  selector:
    matchLabels:
      app: davidgamero-test3
  template:
    metadata:
      labels:
        app: davidgamero-test3
    spec:
      containers:
        - name: davidgamero-test3
          image: acrworkflow1688155414377.azurecr.io/image-workflow-1688155414377:latest
          ports:
            - containerPort: 1323