apiVersion: apps/v1
kind: Deployment
metadata:
  name: davidgamero-test
  labels:
    app: davidgamero-test
  namespace: namespace-workflow-1695050890522
spec:
  replicas: 1
  selector:
    matchLabels:
      app: davidgamero-test
  template:
    metadata:
      labels:
        app: davidgamero-test
    spec:
      containers:
        - name: davidgamero-test
          image: acrworkflow1695050890522.azurecr.io/image-workflow-1695050890522:latest
          ports:
            - containerPort: 80