apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow1
  labels:
    app: workflow1
    kubernetes.azure.com/generator: devhub
  namespace: go-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow1
  template:
    metadata:
      labels:
        app: workflow1
    spec:
      containers:
        - name: workflow1
          image: acrworkflow1726768410299.azurecr.io/image-workflow-1726768410299:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1323
