apiVersion: apps/v1
kind: Deployment
metadata:
  name: av
  labels:
    app: av
  namespace: namespace-workflow-1684345141298
spec:
  replicas: 1
  selector:
    matchLabels:
      app: av
  template:
    metadata:
      labels:
        app: av
    spec:
      containers:
        - name: av
          image: acrworkflow1684345141298.azurecr.io/image-workflow-1684345141298:latest
          ports:
            - containerPort: 801