apiVersion: v1
kind: Service
metadata:
  name: davidgamero-test2
  namespace: namespace-workflow-1695051455078
spec:
  type: LoadBalancer
  selector:
    app: davidgamero-test2
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323