apiVersion: v1
kind: Service
metadata:
  name: workflow1
  namespace: namespace-workflow-1726768769817
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: workflow1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80