apiVersion: v1
kind: Service
metadata:
  name: av
  namespace: namespace-workflow-1684345141298
spec:
  type: LoadBalancer
  selector:
    app: av
  ports:
    - protocol: TCP
      port: 801
      targetPort: 801