apiVersion: v1
kind: Service
metadata:
  name: davidgamero-test
  namespace: namespace-workflow-1678733499614
spec:
  type: LoadBalancer
  selector:
    app: davidgamero-test
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323