apiVersion: v1
kind: Service
metadata:
  name: fffffff
  namespace: namespace-workflow-1732209534853
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: fffffff
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323