apiVersion: v1
kind: Service
metadata:
  name: workflow1
  namespace: go-echo
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: workflow1
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323