apiVersion: v1
kind: Service
metadata:
  name: davidgamero-test3
  namespace: namespace-workflow-1688155414377
spec:
  type: LoadBalancer
  selector:
    app: davidgamero-test3
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323